# https://www.boost.org/
github.com/boostorg/boost=1.92.0
chromium.googlesource.com/chromium/src/buildtools=2d3628028f9b45c97269ee6bd40e3d65eee1ed0e
chromium.googlesource.com/external/github.com/llvm/llvm-project/libcxx=5abc7f839700f0f17338434e1c1c6a8c87c00c11